# Transformation

In [97]:
#import dependencies
import pandas as pd
import json
import requests
import numpy as np

In [98]:
Rental_df = pd.read_csv("Average Rents.csv")
Centres_df = pd.read_csv("Centres.csv")
Zones_df = pd.read_csv("Zones.csv")
Neighbourhood_df = pd.read_csv('Neighbourhood.csv')
Dwelling_df = pd.read_csv('Dwelling.csv')
Province_df =pd.read_csv("Provinces.csv")

In [99]:
Dwelling_df.keys()

Index(['Dwelling_id', 'Dwelling Type'], dtype='object')

In [100]:
Rental_df_copy = Rental_df.copy()

In [101]:
Rental_df_copy.keys()

Index(['Province', 'Centre', 'Zone', 'Neighbourhood', 'Dwelling Type ',
       'Bachelor ', '1 Bedroom', '2 Bedroom', '3 Bedroom +', 'Total ', 'Year'],
      dtype='object')

In [102]:
Rental_df_copy = Rental_df_copy.rename(columns = { "Centre" : "Centres", "Zone" : "Zones" ,'Dwelling Type ' : 'Dwelling Type','Province': 'Provinces'})
Rental_df_copy.keys()

Index(['Provinces', 'Centres', 'Zones', 'Neighbourhood', 'Dwelling Type',
       'Bachelor ', '1 Bedroom', '2 Bedroom', '3 Bedroom +', 'Total ', 'Year'],
      dtype='object')

In [103]:
Rental_cleaned = pd.merge(Rental_df_copy,Province_df, on = 'Provinces' , how = 'left')
Rental_cleaned = pd.merge(Rental_cleaned,Centres_df, on = 'Centres' , how = 'left')
Rental_cleaned = pd.merge(Rental_cleaned,Zones_df, on = 'Zones' , how = 'left')
Rental_cleaned = pd.merge(Rental_cleaned,Neighbourhood_df, on = 'Neighbourhood' , how = 'left')
Rental_cleaned = pd.merge(Rental_cleaned,Dwelling_df, on = 'Dwelling Type' , how = 'left')
Rental_cleaned

,Provinces,Centres,Zones,Neighbourhood,Dwelling Type,Bachelor,1 Bedroom,2 Bedroom,3 Bedroom +,Total,Year,Province_id,Centre_id,Zone_id,Neighbourhood_id,Dwelling_id
0,Nfld.Lab.,St. John's,St. John's East,St. John's East,Row,0.0,783.0,943.0,0.0,1166.0,2018,Province1,centre1,Zone1,Neighbourhood1,Dwelling1
1,Nfld.Lab.,St. John's,St. John's East,St. John's East,Apt & Other,664.0,829.0,1049.0,1002.0,941.0,2018,Province1,centre1,Zone1,Neighbourhood1,Dwelling2
2,Nfld.Lab.,St. John's,St. John's West,St. John's West,Row,0.0,0.0,743.0,0.0,576.0,2018,Province1,centre1,Zone2,Neighbourhood2,Dwelling1
3,Nfld.Lab.,St. John's,St. John's West,St. John's West,Apt & Other,762.0,773.0,881.0,959.0,839.0,2018,Province1,centre1,Zone2,Neighbourhood2,Dwelling2
4,Nfld.Lab.,St. John's,Remainder of CMA,Remainder of CMA,Row,0.0,0.0,0.0,0.0,0.0,2018,Province1,centre1,Zone3,Neighbourhood3,Dwelling1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8945,B.C.,Victoria,Oak Bay,Oak Bay North,Apt & Other,1107.0,1226.0,1679.0,0.0,1405.0,2022,Province9,centre36,Zone269,Neighbourhood859,Dwelling2
8946,B.C.,Victoria,North Saanich,North Saanich,Row,0.0,0.0,0.0,0.0,0.0,2022,Province9,centre36,Zone270,Neighbourhood860,Dwelling1
8947,B.C.,Victoria,North Saanich,North Saanich,Apt & Other,0.0,0.0,0.0,0.0,0.0,2022,Province9,centre36,Zone270,Neighbourhood860,Dwelling2
8948,B.C.,Victoria,Sidney,Sidney,Row,0.0,0.0,0.0,0.0,0.0,2022,Province9,centre36,Zone271,Neighbourhood861,Dwelling1
8949,B.C.,Victoria,Sidney,Sidney,Apt & Other,0.0,1447.0,1753.0,3093.0,1635.0,2022,Province9,centre36,Zone271,Neighbourhood861,Dwelling2

In [104]:
Rental_cleaned.keys()

Index(['Provinces', 'Centres', 'Zones', 'Neighbourhood', 'Dwelling Type',
       'Bachelor ', '1 Bedroom', '2 Bedroom', '3 Bedroom +', 'Total ', 'Year',
       'Province_id', 'Centre_id', 'Zone_id', 'Neighbourhood_id',
       'Dwelling_id'],
      dtype='object')

In [105]:
length_df = (len(Rental_cleaned))

In [106]:
# Create unique ids 
Rent_ID = np.arange(1, length_df + 1)
Rental_id = ['Rent_' + str(each) for each in Rent_ID]
#print(Rental_id)

In [107]:
Rental_cleaned["Rent ID"] = Rental_id

In [108]:
# check data types
Rental_cleaned.dtypes

Provinces            object
Centres              object
Zones                object
Neighbourhood        object
Dwelling Type        object
Bachelor            float64
1 Bedroom           float64
2 Bedroom           float64
3 Bedroom +         float64
Total               float64
Year                  int64
Province_id          object
Centre_id            object
Zone_id              object
Neighbourhood_id     object
Dwelling_id          object
Rent ID              object
dtype: object

In [109]:
Rental_cleaned = Rental_cleaned.rename(columns = { 'Bachelor ': 'Bachelor', 'Total ' : 'Total'})
Rental_cleaned.keys()

Index(['Provinces', 'Centres', 'Zones', 'Neighbourhood', 'Dwelling Type',
       'Bachelor', '1 Bedroom', '2 Bedroom', '3 Bedroom +', 'Total', 'Year',
       'Province_id', 'Centre_id', 'Zone_id', 'Neighbourhood_id',
       'Dwelling_id', 'Rent ID'],
      dtype='object')

In [110]:
Rental_cleaned = Rental_cleaned[['Rent ID','Bachelor', '1 Bedroom', '2 Bedroom', '3 Bedroom +', 'Total', 'Year','Province_id','Centre_id', 'Zone_id', 'Neighbourhood_id', 'Dwelling_id' ]]

In [111]:
Rental_cleaned

,Rent ID,Bachelor,1 Bedroom,2 Bedroom,3 Bedroom +,Total,Year,Province_id,Centre_id,Zone_id,Neighbourhood_id,Dwelling_id
0,Rent_1,0.0,783.0,943.0,0.0,1166.0,2018,Province1,centre1,Zone1,Neighbourhood1,Dwelling1
1,Rent_2,664.0,829.0,1049.0,1002.0,941.0,2018,Province1,centre1,Zone1,Neighbourhood1,Dwelling2
2,Rent_3,0.0,0.0,743.0,0.0,576.0,2018,Province1,centre1,Zone2,Neighbourhood2,Dwelling1
3,Rent_4,762.0,773.0,881.0,959.0,839.0,2018,Province1,centre1,Zone2,Neighbourhood2,Dwelling2
4,Rent_5,0.0,0.0,0.0,0.0,0.0,2018,Province1,centre1,Zone3,Neighbourhood3,Dwelling1
...,...,...,...,...,...,...,...,...,...,...,...,...
8945,Rent_8946,1107.0,1226.0,1679.0,0.0,1405.0,2022,Province9,centre36,Zone269,Neighbourhood859,Dwelling2
8946,Rent_8947,0.0,0.0,0.0,0.0,0.0,2022,Province9,centre36,Zone270,Neighbourhood860,Dwelling1
8947,Rent_8948,0.0,0.0,0.0,0.0,0.0,2022,Province9,centre36,Zone270,Neighbourhood860,Dwelling2
8948,Rent_8949,0.0,0.0,0.0,0.0,0.0,2022,Province9,centre36,Zone271,Neighbourhood861,Dwelling1
8949,Rent_8950,0.0,1447.0,1753.0,3093.0,1635.0,2022,Province9,centre36,Zone271,Neighbourhood861,Dwelling2

In [112]:
Rental_cleaned.to_csv("Rental Data.csv", index=False)

In [113]:
Vacancy_df = pd.read_csv('Vacancy Rates.csv')

In [114]:
Vacancy_df_copy = Vacancy_df.rename(columns = { "Centre" : "Centres", "Zone" : "Zones",'Province': 'Provinces'})
Vacancy_df_copy.keys()

Index(['Provinces', 'Centres', 'Zones', 'Neighbourhood', 'Dwelling Type ',
       'Bachelor ', '1 Bedroom', '2 Bedroom', '3 Bedroom +', 'Total ', 'Year'],
      dtype='object')

In [115]:
Vacancy_df_copy = Vacancy_df_copy.rename(columns = { 'Bachelor ': 'Bachelor', 'Total ' : 'Total', 'Dwelling Type ' : 'Dwelling Type'})
Vacancy_df_copy

,Provinces,Centres,Zones,Neighbourhood,Dwelling Type,Bachelor,1 Bedroom,2 Bedroom,3 Bedroom +,Total,Year
0,Nfld.Lab.,St. John's,St. John's East,St. John's East,Row,0.0,0.0,0.0,0.0,0.0,2018
1,Nfld.Lab.,St. John's,St. John's East,St. John's East,Apt & Other,0.0,3.9,6.4,5.2,5.6,2018
2,Nfld.Lab.,St. John's,St. John's West,St. John's West,Row,0.0,0.0,0.0,0.0,1.5,2018
3,Nfld.Lab.,St. John's,St. John's West,St. John's West,Apt & Other,3.9,6.1,6.1,0.0,6.2,2018
4,Nfld.Lab.,St. John's,Remainder of CMA,Remainder of CMA,Row,0.0,0.0,0.0,0.0,0.0,2018
...,...,...,...,...,...,...,...,...,...,...,...
8945,B.C.,Victoria,Oak Bay,Oak Bay North,Apt & Other,0.0,0.2,1.1,0.0,0.7,2022
8946,B.C.,Victoria,North Saanich,North Saanich,Row,0.0,0.0,0.0,0.0,0.0,2022
8947,B.C.,Victoria,North Saanich,North Saanich,Apt & Other,0.0,0.0,0.0,0.0,0.0,2022
8948,B.C.,Victoria,Sidney,Sidney,Row,0.0,0.0,0.0,0.0,0.0,2022
8949,B.C.,Victoria,Sidney,Sidney,Apt & Other,0.0,0.0,6.9,0.0,0.0,2022

In [122]:
Vacancy_cleaned = pd.merge(Vacancy_df_copy,Province_df, on = 'Provinces' , how = 'left')
Vacancy_cleaned = pd.merge(Vacancy_cleaned,Centres_df, on = 'Centres' , how = 'left')
Vacancy_cleaned = pd.merge(Vacancy_cleaned,Zones_df, on = 'Zones' , how = 'left')
Vacancy_cleaned  = pd.merge(Vacancy_cleaned ,Neighbourhood_df, on = 'Neighbourhood' , how = 'left')
Vacancy_cleaned  = pd.merge(Vacancy_cleaned ,Dwelling_df, on = 'Dwelling Type' , how = 'left')
Vacancy_cleaned

,Provinces,Centres,Zones,Neighbourhood,Dwelling Type,Bachelor,1 Bedroom,2 Bedroom,3 Bedroom +,Total,Year,Province_id,Centre_id,Zone_id,Neighbourhood_id,Dwelling_id
0,Nfld.Lab.,St. John's,St. John's East,St. John's East,Row,0.0,0.0,0.0,0.0,0.0,2018,Province1,centre1,Zone1,Neighbourhood1,Dwelling1
1,Nfld.Lab.,St. John's,St. John's East,St. John's East,Apt & Other,0.0,3.9,6.4,5.2,5.6,2018,Province1,centre1,Zone1,Neighbourhood1,Dwelling2
2,Nfld.Lab.,St. John's,St. John's West,St. John's West,Row,0.0,0.0,0.0,0.0,1.5,2018,Province1,centre1,Zone2,Neighbourhood2,Dwelling1
3,Nfld.Lab.,St. John's,St. John's West,St. John's West,Apt & Other,3.9,6.1,6.1,0.0,6.2,2018,Province1,centre1,Zone2,Neighbourhood2,Dwelling2
4,Nfld.Lab.,St. John's,Remainder of CMA,Remainder of CMA,Row,0.0,0.0,0.0,0.0,0.0,2018,Province1,centre1,Zone3,Neighbourhood3,Dwelling1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8945,B.C.,Victoria,Oak Bay,Oak Bay North,Apt & Other,0.0,0.2,1.1,0.0,0.7,2022,Province9,centre36,Zone269,Neighbourhood859,Dwelling2
8946,B.C.,Victoria,North Saanich,North Saanich,Row,0.0,0.0,0.0,0.0,0.0,2022,Province9,centre36,Zone270,Neighbourhood860,Dwelling1
8947,B.C.,Victoria,North Saanich,North Saanich,Apt & Other,0.0,0.0,0.0,0.0,0.0,2022,Province9,centre36,Zone270,Neighbourhood860,Dwelling2
8948,B.C.,Victoria,Sidney,Sidney,Row,0.0,0.0,0.0,0.0,0.0,2022,Province9,centre36,Zone271,Neighbourhood861,Dwelling1
8949,B.C.,Victoria,Sidney,Sidney,Apt & Other,0.0,0.0,6.9,0.0,0.0,2022,Province9,centre36,Zone271,Neighbourhood861,Dwelling2

In [123]:
# Vacancy_cleaned = Vacancy_merged_df.drop(['Centres','Zones'], axis = 1)
# Vacancy_cleaned.head()
Vacancy_ID = np.arange(1, length_df + 1)
Vacancy_id = ['VR_' + str(each) for each in Vacancy_ID]
Vacancy_cleaned["VR_ID"] = Vacancy_id
Vacancy_cleaned

,Provinces,Centres,Zones,Neighbourhood,Dwelling Type,Bachelor,1 Bedroom,2 Bedroom,3 Bedroom +,Total,Year,Province_id,Centre_id,Zone_id,Neighbourhood_id,Dwelling_id,VR_ID
0,Nfld.Lab.,St. John's,St. John's East,St. John's East,Row,0.0,0.0,0.0,0.0,0.0,2018,Province1,centre1,Zone1,Neighbourhood1,Dwelling1,VR_1
1,Nfld.Lab.,St. John's,St. John's East,St. John's East,Apt & Other,0.0,3.9,6.4,5.2,5.6,2018,Province1,centre1,Zone1,Neighbourhood1,Dwelling2,VR_2
2,Nfld.Lab.,St. John's,St. John's West,St. John's West,Row,0.0,0.0,0.0,0.0,1.5,2018,Province1,centre1,Zone2,Neighbourhood2,Dwelling1,VR_3
3,Nfld.Lab.,St. John's,St. John's West,St. John's West,Apt & Other,3.9,6.1,6.1,0.0,6.2,2018,Province1,centre1,Zone2,Neighbourhood2,Dwelling2,VR_4
4,Nfld.Lab.,St. John's,Remainder of CMA,Remainder of CMA,Row,0.0,0.0,0.0,0.0,0.0,2018,Province1,centre1,Zone3,Neighbourhood3,Dwelling1,VR_5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8945,B.C.,Victoria,Oak Bay,Oak Bay North,Apt & Other,0.0,0.2,1.1,0.0,0.7,2022,Province9,centre36,Zone269,Neighbourhood859,Dwelling2,VR_8946
8946,B.C.,Victoria,North Saanich,North Saanich,Row,0.0,0.0,0.0,0.0,0.0,2022,Province9,centre36,Zone270,Neighbourhood860,Dwelling1,VR_8947
8947,B.C.,Victoria,North Saanich,North Saanich,Apt & Other,0.0,0.0,0.0,0.0,0.0,2022,Province9,centre36,Zone270,Neighbourhood860,Dwelling2,VR_8948
8948,B.C.,Victoria,Sidney,Sidney,Row,0.0,0.0,0.0,0.0,0.0,2022,Province9,centre36,Zone271,Neighbourhood861,Dwelling1,VR_8949
8949,B.C.,Victoria,Sidney,Sidney,Apt & Other,0.0,0.0,6.9,0.0,0.0,2022,Province9,centre36,Zone271,Neighbourhood861,Dwelling2,VR_8950

In [124]:
Vacancy_cleaned = Vacancy_cleaned[['VR_ID','Bachelor', '1 Bedroom', '2 Bedroom', '3 Bedroom +', 'Total', 'Year','Province_id','Centre_id', 'Zone_id', 'Neighbourhood_id', 'Dwelling_id' ]]

In [125]:
Vacancy_cleaned.to_csv("Vacancy Rate Data.csv", index=False)

In [127]:
Units_df = pd.read_csv('Number of Units.csv')
Units_df_copy = Units_df.rename(columns = { "Centre" : "Centres", "Zone" : "Zones", 'Dwelling Type ' : 'Dwelling Type','Province': 'Provinces'})
Units_df_copy = Units_df_copy.rename(columns = { 'Bachelor ': 'Bachelor', 'Total ' : 'Total'})
Units_cleaned = pd.merge(Units_df_copy,Province_df, on = 'Provinces' , how = 'left')
Units_cleaned = pd.merge(Units_cleaned,Centres_df, on = 'Centres' , how = 'left')
Units_cleaned = pd.merge(Units_cleaned,Zones_df, on = 'Zones' , how = 'left')
Units_cleaned  = pd.merge(Units_cleaned ,Neighbourhood_df, on = 'Neighbourhood' , how = 'left')
Units_cleaned = pd.merge(Units_cleaned ,Dwelling_df, on = 'Dwelling Type' , how = 'left')

Units_ID = np.arange(1, length_df + 1)
Units_id = ['Units_' + str(each) for each in Units_ID]
Units_cleaned["Units_ID"] = Units_id

Units_cleaned

#Units_cleaned = Units_merged_df.drop(['Centres','Zones'], axis = 1)
Units_cleaned.head()

,Provinces,Centres,Zones,Neighbourhood,Dwelling Type,Bachelor,1 Bedroom,2 Bedroom,3 Bedroom +,Total,Year,Province_id,Centre_id,Zone_id,Neighbourhood_id,Dwelling_id,Units_ID
0,Nfld.Lab.,St. John's,St. John's East,St. John's East,Row,1.0,22.0,16.0,16.0,55.0,2018,Province1,centre1,Zone1,Neighbourhood1,Dwelling1,Units_1
1,Nfld.Lab.,St. John's,St. John's East,St. John's East,Apt & Other,203.0,641.0,1015.0,107.0,1966.0,2018,Province1,centre1,Zone1,Neighbourhood1,Dwelling2,Units_2
2,Nfld.Lab.,St. John's,St. John's West,St. John's West,Row,0.0,46.0,21.0,0.0,67.0,2018,Province1,centre1,Zone2,Neighbourhood2,Dwelling1,Units_3
3,Nfld.Lab.,St. John's,St. John's West,St. John's West,Apt & Other,149.0,427.0,859.0,126.0,1561.0,2018,Province1,centre1,Zone2,Neighbourhood2,Dwelling2,Units_4
4,Nfld.Lab.,St. John's,Remainder of CMA,Remainder of CMA,Row,0.0,0.0,64.0,6.0,70.0,2018,Province1,centre1,Zone3,Neighbourhood3,Dwelling1,Units_5

In [128]:
Units_cleaned = Units_cleaned[['Units_ID','Bachelor', '1 Bedroom', '2 Bedroom', '3 Bedroom +', 'Total', 'Year','Province_id','Centre_id', 'Zone_id', 'Neighbourhood_id', 'Dwelling_id' ]]

In [129]:
Units_cleaned.to_csv("Number of Units Data.csv", index=False)

## Check datatypes for schema creation

In [67]:
Zones_df.dtypes

Zone_id    object
Zones      object
dtype: object

In [68]:
Vacancy_cleaned.dtypes

VR_ID                object
Bachelor            float64
1 Bedroom           float64
2 Bedroom           float64
3 Bedroom +         float64
Total               float64
Year                  int64
Centre_id            object
Zone_id              object
Neighbourhood_id     object
Dwelling_id          object
dtype: object

In [69]:
Rental_cleaned.dtypes

Rent ID              object
Bachelor            float64
1 Bedroom           float64
2 Bedroom           float64
3 Bedroom +         float64
Total               float64
Year                  int64
Centre_id            object
Zone_id              object
Neighbourhood_id     object
Dwelling_id          object
dtype: object

In [70]:
Units_cleaned.dtypes

Units_ID             object
Bachelor            float64
1 Bedroom           float64
2 Bedroom           float64
3 Bedroom +         float64
Total               float64
Year                  int64
Centre_id            object
Zone_id              object
Neighbourhood_id     object
Dwelling_id          object
dtype: object